workspace/library/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
  get 'post', to: 'animals#post'
  resources :animals
  resources :ingredients
end

workspace/library/app/models/animal.rb
class Animal < ApplicationRecord
end

workspace/library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

workspace/library/app/models/dress.rb
class Dress < ApplicationRecord
end

workspace/library/app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

workspace/library/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  #by including this line, we can remove the following line:
  #@animal = Animal.find(params[:id])
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  respond_to? :html, :js
  def new
    @animal = Animal.new
  end

  def index
    @animals = Animal.all
  end
  def edit
  end
  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      flash[:notice] = "Animal picture has been created."
      redirect_to @animal
    else
      flash.now[:alert] = "Project has not been created."
      render "new"
    end
  end
  def post

  end
  def show
    @image_url = "/assets/animal" + @animal.id.to_s + ".png"
  end

  def update
    @animal.update(animal_params)

    flash[:notice] = "Animal has been updated"
    redirect_to @animal
  end

  def delete
    @animal.destroy
    flash[:notice] = "Animal has been deleted."
    redirect_to animals_path
  end

  private
  def set_animal
    @animal = Animal.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The animal you are looking for cannot be found."
    redirect_to animals_path
  end
  def animal_params
    params.require(:animal).permit(:name,:description,:age)
  end
end

workspace/library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

workspace/library/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end
end

workspace/library/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def about
  end
end

workspace/library/app/helpers/animals_helper.rb
module AnimalsHelper
end

workspace/library/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/library/app/helpers/dresses_helper.rb
module DressesHelper
end

workspace/library/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

workspace/library/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

workspace/library/app/views/animals/_form.html.erb
<%= form_for(animal) do |f| %>
<% if animal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(project.errors.count, "error")%>
      prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
        <%end%>
      </ul>
  </div>
  <%end%>
  <p>
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_field :description %>
  </p>
  <%= f.submit%>
<%end%>  

workspace/library/app/views/animals/edit.html.erb
<h1>Edit Animal</h1>
<%= render "form", animal: @animal%>

workspace/library/app/views/animals/index.html.erb
<h1>Index</h1>
<ul><%=link_to "Create Animal", new_animal_path, class:"btn btn-success"%></ul>
<%@animals.each do |animal|%>
<%=link_to animal.name, animal_path(animal,age:"20")%>
<%=animal.description%>
<%end%>

workspace/library/app/views/animals/new.html.erb
<h1>New Animal</h1>
<%=render "form", animal:@animal%>

workspace/library/app/views/animals/post.html.erb
<h1>Post</h1>

workspace/library/app/views/animals/show.html.erb
<h1><%=@animal.name%></h1>
<p><%=@animal.description%></p>
<%= image_tag(@image_url, :alt => "animal") %>
<ul><%= link_to "Edit Animal", edit_animal_path(@animal), class:"btn btn-info"%></ul>
<ul><%=link_to "Go back to index", animals_path, class:"btn btn-info" %></ul>
<ul><%=link_to "Delete Animal",animal_path(@animal),class:"btn btn-info",
method: :delete, data: { confirm: "Are you sure you want to delete this animal?"}%></ul>
<ul><%=link_to "Home", root_path, class:"btn btn-info"%></ul>

workspace/library/app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<h2 style="font-style:italic;">Raw Cacao Powder</h2>
<h5>Why?</h5>
<p> Super trendy at the moment. High in antioxidants, and minerals such as magnesium and iron.</p>
<h5>How?</h5>
<p>Made from cacao beans. Milled into a fine powder at low temperatures, which maximises the preservation of nutrients
  and flavour</p>
<h5>Sensory profile</h5>
<p>Chocolatey with a bitter after taste. </p>
<h5>References</h5>
<li>http://navitasnaturals.com/product/441/Cacao-Powder.html</li>
<li>Natural news- http://www.naturalnews.com/041916_cacao_scientific_research_health_benefits.html</li>
<li>'The effectiveness and cost effectiveness of dark chocolate consumption as prevention therapy in people at high risk of cardiovascular disease'- https://www.ncbi.nlm.nih.gov/pubmed/22653982</li>
<h2 style="font-style:italic;">Avocado</h2>
<h5>Why?</h5>
<p> High level of antioxidants and high fibre content. Also assists in the absorption of carotenoids
of other vegetables like lettuce, carrot, spinach and others. </p>
<p>Two thirds of fat in avocado is monounsaturated fat- contributes to lowering cholestrol levels. Low in salt, excellent source of folate. </p>
<h5>How?</h5>
<p>Grown in Australia. Peak season is March to September, but available all year round.</p>
<h5>Sensory profile</h5>
<p>Soft, quite bland. More of a base type ingredient. Used as a substitute for dairy products.</p>
<h5>References</h5>
<li>http://daa.asn.au/for-the-public/smart-eating-for-you/nutrition-a-z/avocados/</li>
<li>http://www.nutritionsecrets.com/how-much-avocado-eat-daily/</li>
<h2 style="font-style:italic;">Cottage cheese</h2>
<h5>Why?</h5>
<p>Low carb, high in protein. </p>
<h5>How?</h5>
<p>You can actually make your own. Apparently it's pretty easy.</p>
<h5>Sensory profile</h5>
<p>Tastes a bit more like yoghurt, which was a bit disappointing for a type of cheese. Again, more of a base type ingredient.</p>
<h5>References</h5>

workspace/library/app/views/layouts/_column.html.erb
<div class="btn-group-vertical">
  <ul><%=link_to "About", about_path %></ul>
  <ul><%=link_to "Ingredients", ingredients_path %></ul>
  <ul><%=link_to "Animals", animals_path %></ul>
  <ul>Articles</ul>
  <ul><%=link_to "Contact", contact_path %></ul>
  <ul><%=link_to "Post", post_path %></ul>
</div>

workspace/library/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">myFoodDiaries</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%=link_to "Home", root_path%></li>
      <li><%=link_to "About", about_path%></li>
      <li><%=link_to "Contact", contact_path%></li>
    </ul>
    <form class="navbar-form navbar-right">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
</nav>

workspace/library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myFoodDiaries</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body class='<%=controller.controller_name%>'>
    <%=render partial:"layouts/header"%>
    <div class="row">
      <div class="col-sm-1">
        <% if action_name != "home"%>
          <%=render partial:"layouts/column"%>
        <% end %>
      </div>
      <div class="col-sm-8">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

workspace/library/app/views/static_pages/about.html.erb
<h1>About</h1>
<blockquote cite="http://www.worldwildlife.org/who/index.html">
My cooking skills are limited. I am also trying to improve my programming skills. So I thought I'd
kill two birds with one stone and make a website about learning how to cook. Enjoy!
</blockquote>

workspace/library/app/views/static_pages/contact.html.erb
<h1>Contact</h1>

workspace/library/app/views/static_pages/home.html.erb
<h1 id="main-heading">myFoodDiaries</h1>
<img src="assets/chipmunk.jpg" alt="chipmunk">